### ISSUE TITLE
contour ClusterRoleBinding is duplicated

### ISSUE THREAD

**Issue by bryanl** [knative/net-contour#53]
In https://github.com/knative/net-contour/releases/download/v0.13.0/contour.yaml, ClusterRoleBinding `contour` is duplicated. This doesn't break `kubectl` but will trip up tools like helm and kapp. 

I believe these should be combined.

```yaml
# line 1298
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour
---
# line 2983
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour
subjects:
- kind: ServiceAccount
  name: contour
  namespace: contour-internal
```
